spring.application.name=java-service
spring.datasource.url=jdbc:postgresql://localhost:5432/center
spring.datasource.username=root
spring.datasource.password=2112
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
